spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update

    datasource:
        url: jdbc:mysql://localhost:3306/startrex-kbase
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver

    jackson:
        serialization:
            INDENT_OUTPUT: true
            
    redis:
        host: localhost
        password: secret
        port: 6379


jwt:
    header: Authorization
    secret: mySecret
    expiration: 604800
    route:
        authentication:
            path: auth
            refresh: refresh